CMS_HOST: studio.local.overhang.io
CMS_OAUTH2_SECRET: SIu1FNJpbkHav4YBXWyNaXnU
CONTACT_EMAIL: contact@local.overhang.io
ENABLE_HTTPS: false
ID: 0LS5LGbAiZ3HOetkgSVlOfx1
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEpAIBAAKCAQEAtGcMh9K6nxEIN+5SGJ555bVQ1O9CYZsOwMlQvcrkTVUtwjbb

  zlsw3E97cCtgoLWUmxNX29xUODG1YE4F+IjPLA0HohjkhvQQugGopmRqUDqIrbsn

  JZJ46klKAhCYyU0xfajiBD+sjwm03Aw2Cp+Ipw3ZtxioGOxXaLJM3A1AOFm4J0yz

  fopryX6gU8RWv+OJ4H3ZniVFzSdOiB2SnKR4jCBAGDWeu+y0UK5zsR1p1tqHWD1O

  ++Wtn6vCSz7WNDHQLvNHPuENs1QOK1W21eBpArM9sSEehsAZPTjzRT+tuJUThgBc

  3qlzXT6/bT+qCxJZzIGVOwXvdv5Deuv2xMpC+QIDAQABAoIBAC7esxe6vTfEkhEN

  /xBcZCk1IWohO2rmgT+/ThXxV71ryvaxkAweDyS+FcD/1BwM8S4VKXd61/q9l3UM

  8GoxCTpVrE0GEKGrWYkqEyof3qs3eflBLZuKYZXlMrA0pa1vO9N9BDO8Y1XKXM3q

  8kNyTWuxooX6hvnqtY8C/AsT+kJpRSKWpngXObQV89IxqnfBiQyvfutdh2oYBL03

  UnjLCWFFCVy39416a7rBvzWOwQVVeXXPAy347TzTwiAuztLMylUG1i22tJZw3b/e

  1MO9CPCtk5PiK7BZR1RE3SsZg5FC8YXHlyPVZw7mxnR07nZXvtRSHjOSLeCis7BK

  9rs8Iy0CgYEAyz9tfjG2CpKjdJ9Ufw+msShhnmrUxqzwXNar/hn/SB8oQIt/uCSh

  pJnY3cV/Gib5Bf5J1Kwd43jOz5v7UIP5dSnX66lMowxEBW/lzRrut9lJjzGMeFjH

  1I3AwxqDxCFuFBF0EK/bQbyfDdaVFGJ1VXFJykjm9pDjZWFGBxkeL1sCgYEA4zmx

  /0xpyPsVFjPhe1KKNEswXnWgeIQhXxlRtfJBzjpTJUaoZTGNWOqq6r4yyaYw4LqS

  1VVbVuXKufGRoPAE60SYzmXcTybHFOoYzlfSXTInx5WzasTJKy2MtEto5P49QLnj

  M2YcYI/cwqJ6XmaulxyF5DWMB2zmSRbERsAAWzsCgYEAkO2tmerAsFFYFPT4P5Jd

  fr4YvenXx8PRsaGyCwNmsXrmLQBMFnaofMLnjVwjAfcAY3GsG+aPeYDPl+LWFdfF

  rfIkcXrLlwhMCMR9zP+Dcb2TYnQmgjpsY/igl370ropYAB9h7/Q2GG3zzN5Sd7Kt

  kDu0LnZFm1Q9kjEGylDy4TkCgYEAkO3221iYzIlhfMTgl/Egl5QxqL4r+VKFmoui

  s4Nud6R57fewZsMBXepn08w2xqmK2XwHNaz40mdFM+6hrV4KNSmOsW8E4zNfnbZm

  1g3r7meUOdgBFSOpEDJAYasLn6uN1B/8i4cgqHJ6I2bQ2C90Qov91n5U71OFWq77

  yAik8YsCgYA99bBOAuUB5OuMpKjoP8UVZoQrP6TSkLlGrAKlDcnbs+WDb7ddJD65

  OIO/+n7ubUMqV4Rdefw0ZUa2AgIOcXpkXkVGppSmPkowEoj0hVltPHFK35kFY9hI

  zZ5uWKQLTVr0C9P01tdGjiG3f0/xlQBmNRfhPJTs8oTueUmuQB8wYQ==

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: zh-cn
LMS_HOST: local.overhang.io
MYSQL_ROOT_PASSWORD: e4lMUUFB
OPENEDX_MYSQL_PASSWORD: JeNM8c9q
OPENEDX_SECRET_KEY: JJkZoBb7uoq2zo6QLhw3PgaG
PLATFORM_NAME: My Open edX
PLUGINS:
- mfe
